### PR TITLE
OPSEXP-700: Fix helm related pre-commit checks

### PR DESCRIPTION
**Pull request by gavincornwell**
OPSEXP-700 Pre commit hooks are cached on install or first run which can cause undesirable results when trying to update the hooks themselves therefore removed caching from build and manually delete the folder before running checks.

Furthermore, the "entry" property in .pre-commit-hooks.yaml needs to be a single quoted string.

Finally, the kubebug checks were running against a cluster and not the provided input files.

### CODE REVIEW

**Comment by mteodori** [comment]
@gavincornwell is it correct to remove the cache for pre-commit or maybe enough not to use the branch as ref in .pre-commit.config.yml but always the short sha as in `git rev-parse --short HEAD`?

**Comment by gavincornwell** [comment]
@mteodori No, it's not enough, changing the ref to *anything* has no effect once the pre-commit hooks have been run once, this silent failure to fetch the latest code from the remote repo is what caused to me spend ages on this problem!

As this will only run once per build I'm not sure having it cached is that important to be honest.

**Comment by mteodori** [comment]
> @mteodori No, it's not enough, changing the ref to _anything_ has no effect once the pre-commit hooks have been run once, this silent failure to fetch the latest code from the remote repo is what caused to me spend ages on this problem!
> 
> As this will only run once per build I'm not sure having it cached is that important to be honest.

maybe we have to measure, but on the same PR I would avoid to download the same hooks multiple times
I am a bit skeptic about the lack of effect of rev as I would see the same behaviour locally and also other Travis builds I have seen the changes applied

**Comment by gavincornwell** [comment]
Ah, actually I see what you mean, if you changed the rev *every* time you made a change in the alfresco-build-tools I can see how that might work, I haven't tried that myself.

I will revert the cache changes.

**Review by mteodori — APPROVED** [review]

**Pull request merged**
