### PR TITLE
remove pre-commit action OPSEXP-1466

### PR DESCRIPTION
**Pull request by himanshu-nigam**

### CODE REVIEW

**Comment by alxgomz** [comment]
> Hi, this action is referenced in a lot of repositories, for instance here: https://github.com/Alfresco/alfresco-process/blob/develop/.github/workflows/build.yml#L19. What's the issue with it that requires removal please? Thanks

It's been decided not to create actions if they're simple wrapper and don't bring additionnal value. Here there's no reason why not using the upstream github action. (https://github.com/Alfresco/alfresco-ansible-deployment/pull/294#issuecomment-1117593846)

**Review by alxgomz — CHANGES_REQUESTED** [review]
Please make sure to remove the pre-commit **action** related (not related this repo's pre-commit) doc in the readme file.

**Comment by alxgomz** [comment]
@mteodori , @erdemedeiros ' comment make sense and beyond that, we will find situations where subsequent jobs and steps in Actions rely on the fact repo has already been checked-out and (less likely) python setup...
I would consider that a valid reason to keep that action even though it doesn't provide a huge value

**Review by gionn — CHANGES_REQUESTED** [review]
in the end I will keep it too, not for the current value but for the future improvements potential: we could use it to enforce some pre-commit checks across all the org in a centralized manner.

**Comment by himanshu-nigam** [comment]
Changes not required , keeping Pre-commit for future improvements

**Pull request closed without merging**
