### PR TITLE
[AAE-15797] add action for processing coverage report using jacoco-report plugin

### PR DESCRIPTION
**Pull request by indrayanganguly**

### CODE REVIEW

**Review by mavotto — COMMENTED** [review]
I had thought of creating a more generic action, for example a "process coverage report" action, not one specific to the jacoco report plugin. In the future we will also use sonarcloud and could add it within this action without any other changes. What do you think?

**Review by mavotto — APPROVED** [review]
LGTM

**Review by gionn — CHANGES_REQUESTED** [review]
please document it in the README

**Comment by indrayanganguly** [comment]
> I had thought of creating a more generic action, for example a "process coverage report" action, not one specific to the jacoco report plugin. In the future we will also use sonarcloud and could add it within this action without any other changes. What do you think?

changed the name of action to process-coverage-report

**Comment by indrayanganguly** [comment]
> please document it in the README

updated the documentation

**Review by gionn — COMMENTED** [review]
just update the PR title according to the new name and it's good for me

**Comment by indrayanganguly** [comment]
> just update the PR title according to the new name and it's good for me

Updated.

**Review by mavotto — APPROVED** [review]

**Pull request merged**
